<a href="https://colab.research.google.com/github/ramaalfin/modul_python/blob/master/modul_python_R.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
print('contoh string yang dibuat menggunakan kutip satu')

contoh string yang dibuat menggunakan kutip satu


In [ ]:
print("contoh string yang dibuat menggunakan kutip dua")

contoh string yang dibuat menggunakan kutip dua


In [ ]:
'ini adalah string tanpa menggunakan print() - 1'

'ini adalah string tanpa menggunakan print() - 1'

In [ ]:
"ini adalah string tanpa menggunakan print() - 2"

'ini adalah string tanpa menggunakan print() - 2'

In [ ]:
print("")

In [ ]:
print('')

In [ ]:
""


''

In [ ]:
''

''

In [ ]:
print('My father's clothes')

SyntaxError: ignored

In [ ]:
print("I said, "good bye!" ")

SyntaxError: ignored

In [ ]:
print("My father's clothes")

My father's clothes


In [ ]:
print('I said, "welcome!" ')

I said, "welcome!" 


In [ ]:
print('My father\'s clothes')

My father's clothes


In [ ]:
print("I said, \"good morning!\" ")

I said, "good morning!" 


In [ ]:
print(123)

123


In [ ]:
10

10

In [ ]:
print(-27)

-27


In [ ]:
print(0.1)

0.1


In [ ]:
-1.2

-1.2

In [ ]:
print(.50)

0.5


In [ ]:
print(.23)

0.23


In [ ]:
print(.5)

0.5


In [ ]:
print(3.)

3.0


In [ ]:
3.

3.0

In [ ]:
print(1 == 2)

False


In [ ]:
1 == 2

False

In [ ]:
print(2 == 2)

True


In [ ]:
2 == 2

True

In [ ]:
print("Dia" == 'dia')

False


In [ ]:
"Dia" == 'dia'

False

In [ ]:
print('saya' == 'saya')

True


In [ ]:
'saya' == 'saya'

True

In [ ]:
type(1)

int

In [ ]:
type(-1)

int

In [ ]:
type(0.1)

float

In [ ]:
type('ini buku')

str

In [ ]:
type(1 == 2)

bool

In [ ]:
type(False)

bool

In [ ]:
type(1)

int

In [ ]:
float(1)

1.0

In [ ]:
type(float(1))

float

In [ ]:
int(2.3)

2

In [ ]:
int(-2.7)

-2

In [ ]:
int(76.75)

76

In [ ]:
int('12')

12

In [ ]:
int('-1')

-1

In [ ]:
float('11.2')

11.2

In [ ]:
float('-11.2')

-11.2

In [ ]:
int('15 derajat')

ValueError: ignored

In [ ]:
float('1.5 dan 2.5')

ValueError: ignored

In [ ]:
str(123)

'123'

In [ ]:
str(-123)

'-123'

In [ ]:
str(12.34)

'12.34'

In [ ]:
int(True)

1

In [ ]:
int(False)

0

In [ ]:
float(True)

1.0

In [ ]:
float(False)

0.0

In [ ]:
bool(1)

True

In [ ]:
bool(0)

False

In [ ]:
bool(1.0)

True

In [ ]:
bool(0.0)

False

EKSPRESI

In [ ]:
12 + 23

35

In [ ]:
12 + 34 + 45

91

In [ ]:
x = 10

In [ ]:
y = 20

In [ ]:
x + y # Ekspresi penjumlahan dengan operand berupa variabel

30

In [ ]:
x + y + 25 # Ekspresi penjumlahan dengan operand berupa variabel dan angka 

55

In [ ]:
10 - 5

5

In [ ]:
100 - 25 -10

65

In [ ]:
x = 20

In [ ]:
y = 10

In [ ]:
x - y # Ekspresi pengurangan dengan operand berupa variabel

10

In [ ]:
x - y - 2 # Ekspresi pengurangan dengan operand berupa variabel dan angka 

8

In [ ]:
2 * 2

4

In [ ]:
2 * 2 * 5

20

In [ ]:
x = 20
y = 10
x * y

200

In [ ]:
x * 5 # Ekspresi perkalian dengan operand berupa variabel

100

In [ ]:
10 / 2

5.0

In [ ]:
10 / 2 /5

1.0

In [ ]:
x = 20
y = 10 
x / y # Ekspresi modulo dengan operand berupa variabel dan angka 

2.0

In [ ]:
x / 5 # Ekspresi pembagian dengan operand berupa variabel dan angka

4.0

In [ ]:
10 % 2

0

In [ ]:
10 % 4

2

In [ ]:
x = 20 
y = 10 
x % y # Ekspresi modulo dengan operand berupa variabel

0

In [ ]:
x % 3 # Ekspresi modulo dengan operand berupa variabel dan angka 

2

In [ ]:
10 // 4

2

In [ ]:
20 // 5

4

In [ ]:
x = 20 
y = 10 
x // y

2

In [ ]:
9 // 4

2

In [ ]:
9 // -4

-3

In [ ]:
2 ** 3 # Dua pangkat Tiga

8

In [ ]:
x = 10
y = 2
x ** y # x pangkat y

100

In [ ]:
x ** 3

1000

In [ ]:
5 ** y

25

In [ ]:
(10 + 15) * 8 / 4

50.0

In [ ]:
20 / (4 - 2)

10.0

In [ ]:
20 / 4 - 2

3.0

In [ ]:
a = 10 
b = 2 
c = 3 
(a + b) * c

36

In [ ]:
a + b * c

16

List

In [ ]:
x = [1, 2, 3] 
print(x)

[1, 2, 3]


In [ ]:
vegetables = ['carrot', 'cucumber', 'potato']
print(vegetables)

['carrot', 'cucumber', 'potato']


In [ ]:
y = ['Doe', 21, False, 2.1]
print(y)

['Doe', 21, False, 2.1]


In [ ]:
vegetables = ['carrot', 'cucumber', 'potato'] 
vegetables[1]

'cucumber'

In [ ]:
vegetables[-1]

'potato'

In [ ]:
print(vegetables[2])

potato


In [ ]:
vegetables = ['carrot', 'cucumber', 'spinach','cabbage','beans'] 
vegetables[0:3]

['carrot', 'cucumber', 'spinach']

In [ ]:
vegetables[0:1]

['carrot']

In [ ]:
print(vegetables[2:4])

['spinach', 'cabbage']


In [ ]:
vegetables = ['carrot', 'cucumber', 'spinach','cabbage','beans'] 

In [ ]:
vegetables[::4]

['carrot', 'beans']

In [ ]:
vegetables[0::3]

['carrot', 'cabbage']

In [ ]:
vegetables [1:2:2]

['cucumber']

In [ ]:
a = [[1, 2], [3,4], [5,6]] 
a

[[1, 2], [3, 4], [5, 6]]

In [ ]:
b = [1, 'carrot', ['x', 'y'], 10.5, [10, 30]] 
print(b)

[1, 'carrot', ['x', 'y'], 10.5, [10, 30]]


In [ ]:
b = [1, 'carrot', ['x', 'y'], 10.5, [10, 30]] 
b[4][1]


30

In [ ]:
b[4][0]

10

In [ ]:
b[2][1]

'y'

In [ ]:
b[2][0]

'x'

In [ ]:
vegetables = ['carrot', 'cucumber', 'spinach','cabbage','beans'] 
vegetables

['carrot', 'cucumber', 'spinach', 'cabbage', 'beans']

In [ ]:
vegetables[3] = 'brocoli' # Mengubah isi indeks 3 menjadi 'brocoli' 
vegetables 

['carrot', 'cucumber', 'spinach', 'brocoli', 'beans']

In [ ]:
vegetables[3] = 'brocoli' # Mengubah isi indeks 3 menjadi 'brocoli' 
vegetables 

['carrot', 'cucumber', 'spinach', 'brocoli', 'beans']

In [ ]:
# Menambahkan nilai 1 dan 2 pada akhir list vegetables 
vegetables = ['carrot', 'asparagus', 'spinach','brocoli','beans']
vegetables = vegetables + [1, 2] 
vegetables

['carrot', 'asparagus', 'spinach', 'brocoli', 'beans', 1, 2]

In [ ]:
# Menambahkan 'cabbage' pada awal list vegetables 
vegetables = ['cabbage'] + vegetables 
print(vegetables )

['cabbage', 'carrot', 'asparagus', 'spinach', 'brocoli', 'beans', 1, 2]


In [ ]:
vegetables = ['carrot', 'asparagus', 'spinach','brocoli','beans']
vegetables.append('cabbage')
vegetables

['carrot', 'asparagus', 'spinach', 'brocoli', 'beans', 'cabbage']

In [ ]:
vegetables = ['carrot', 'asparagus', 'spinach','brocoli','beans']
a = vegetables.append('cabbage')
a

In [ ]:
vegetables = ['carrot', 'asparagus', 'spinach','brocoli','beans']
vegetables.extend('cabbage')
print(vegetables)

['carrot', 'asparagus', 'spinach', 'brocoli', 'beans', 'c', 'a', 'b', 'b', 'a', 'g', 'e']


In [ ]:
vegetables = ['carrot', 'asparagus', 'spinach','brocoli','beans']
vegetables.extend(['cabbage'])
print(vegetables)

['carrot', 'asparagus', 'spinach', 'brocoli', 'beans', 'cabbage']


In [ ]:
vegetables = ['carrot', 'asparagus', 'spinach','brocoli','beans']
vegetables.insert(1, 'cabbage')
print(vegetables)

['carrot', 'cabbage', 'asparagus', 'spinach', 'brocoli', 'beans']


In [ ]:
vegetables = ['carrot', 'asparagus', 'spinach','brocoli','beans']
del vegetables[2]
vegetables

['carrot', 'asparagus', 'brocoli', 'beans']

In [ ]:
vegetables = ['carrot', 'asparagus', 'spinach','brocoli','beans']
vegetables.remove('brocoli')
vegetables

['carrot', 'asparagus', 'spinach', 'beans']

In [ ]:
vegetables = ['carrot', 'asparagus', 'spinach','brocoli','beans']
vegetables.pop(2)
vegetables

['carrot', 'asparagus', 'brocoli', 'beans']

In [ ]:
vegetables = ['carrot', 'asparagus', 'spinach','brocoli','beans']
vegetables.pop()
vegetables

['carrot', 'asparagus', 'spinach', 'brocoli']

Dictionary

In [ ]:
a = {1: 'a', 2: 'b', (3,4): 'c'}
a

{(3, 4): 'c', 1: 'a', 2: 'b'}

In [ ]:
data_siswa = {
    'nama': 'Ira',
    'kota': 'Bogor',
    'umur': 20
    }
data_siswa

{'kota': 'Bogor', 'nama': 'Ira', 'umur': 20}

In [ ]:
data_siswa = {
    'nama': 'Ira',
    'kota': 'Bogor',
    'umur': 20
    }
data_siswa['nama'] # Mengakses value dengan key 'nama'

'Ira'

In [ ]:
data_siswa['kota']

'Bogor'

In [ ]:
data_siswa.get('nama')

'Ira'

In [ ]:
data_siswa.get('kota')

'Bogor'

In [ ]:
data_siswa.values()

dict_values(['Ira', 'Bogor', 20])

In [ ]:
data_siswa.keys()

dict_keys(['nama', 'kota', 'umur'])

In [ ]:
[*data_siswa]

['nama', 'kota', 'umur']

In [ ]:
students = {'student1': {'name': 'Doe', 'age': 30},
            'student2': {'name': 'Robert', 'age': 31},
            'student3': {'name': 'Andy', 'age': 33}
            }
students 

{'student1': {'age': 30, 'name': 'Doe'},
 'student2': {'age': 31, 'name': 'Robert'},
 'student3': {'age': 33, 'name': 'Andy'}}

In [ ]:
student1 = {'name': 'Doe', 'age': 30}
student2 = {'name': 'Robert', 'age': 31}
student3 = {'name': 'Andy', 'age': 33}

students= {
 'student1': student1,
 'student2': student2,
 'student3': student3
}
students

{'student1': {'age': 30, 'name': 'Doe'},
 'student2': {'age': 31, 'name': 'Robert'},
 'student3': {'age': 33, 'name': 'Andy'}}

In [ ]:
data_siswa = {
    'nama': 'Ira',
    'kota': 'Bogor', 
    'umur': 20
}
data_siswa['kota'] = 'Bandung' # Mengubah data kota
data_siswa

{'kota': 'Bandung', 'nama': 'Ira', 'umur': 20}

In [ ]:
data_siswa['umur'] = 21 # Mengubah data umur
data_siswa 

{'kota': 'Bandung', 'nama': 'Ira', 'umur': 21}

In [ ]:
students = {
    'student1' : {'name': 'Doe', 'age': 30},
    'student2' : {'name': 'Robert', 'age': 31},
    'student3' : {'name': 'Andi', 'age': 32}
    }
    
students['student3']['age'] = 34 # Mengubah nilai age
students

{'student1': {'age': 30, 'name': 'Doe'},
 'student2': {'age': 31, 'name': 'Robert'},
 'student3': {'age': 34, 'name': 'Andi'}}

In [ ]:
data_siswa = {
    'nama': 'Ira',
    'kota': 'Bogor',
    'umur': 20
}
data_siswa ['jurusan'] = 'Teknik Informatika' # Menambahkan key 'jurusan' yang diberikan nilai 'Teknik Informatika'
data_siswa

{'jurusan': 'Teknik Informatika', 'kota': 'Bogor', 'nama': 'Ira', 'umur': 20}

In [ ]:
data_siswa = {
    'nama': 'Ira',
    'kota': 'Bogor',
    'umur': 20,
    'jurusan':'Teknik Informatika'
}
data_siswa.pop('kota') # Menghapus kota
print(data_siswa)

{'nama': 'Ira', 'umur': 20, 'jurusan': 'Teknik Informatika'}


In [ ]:
data_siswa = {
    'nama': 'Ira',
    'kota': 'Bogor',
    'umur': 20,
    'jurusan':'Teknik Informatika'
}

data_siswa.popitem() # Method popitem() akan menghapus nilai akhir
print(data_siswa)

{'nama': 'Ira', 'kota': 'Bogor', 'umur': 20}


In [ ]:
data_siswa = {
    'nama': 'Ira',
    'kota': 'Bogor',
    'umur': 20,
    'jurusan':'Teknik Informatika'
}
del data_siswa['umur'] # Menghapus umurmenggunakan del
print(data_siswa)

{'nama': 'Ira', 'kota': 'Bogor', 'jurusan': 'Teknik Informatika'}


In [ ]:
data_siswa = {
    'nama': 'Ira',
    'kota': 'Bogor',
    'umur': 20,
    'jurusan':'Teknik Informatika'
}
del data_siswa # Menghapus dictionary data_siswa
print(data_siswa)

NameError: ignored

In [ ]:
data_siswa = {
    'nama': 'Ira',
    'kota': 'Bogor',
    'umur': 20,
    'jurusan':'Teknik Informatika'
}
data_siswa.clear() # Mengosongkan isi dictionary dengan clear()
print(data_siswa)

{}


In [ ]:
data_siswa = {
    'nama': 'Ira',
    'kota': 'Bogor',
    'umur': 20,
    'jurusan':'Teknik Informatika'
}
# Menduplikasi 'data_siswa' ke dalam dictionary baru ke dalam 'siswa'
siswa = data_siswa.copy() 
print(siswa)

{'nama': 'Ira', 'kota': 'Bogor', 'umur': 20, 'jurusan': 'Teknik Informatika'}


In [ ]:
data_siswa = {
    'nama': 'Ira',
    'kota': 'Bogor',
    'umur': 20,
    'jurusan':'Teknik Informatika'
}

len(data_siswa) # Menghitung panjang dictionary (jumlah item)

4

In [ ]:
data_siswa = {
    'nama': 'Ira',
    'kota': 'Bogor',
    'umur': 20,
    'jurusan':'Teknik Informatika'
}

'nama' in data_siswa # Mengecek apakah 'nama' ada sebagai key di data_siswa 

True

In [ ]:
'hobi' in data_siswa

False

Seleksi Kondisi

In [ ]:
a = 2 
a == 4 # Contoh penggunaan operator ==

False

In [ ]:
a = 2
a != 4 # Contoh penggunaan operator !=

True

In [ ]:
a = 2
a > 4 # Contoh penggunaan operator >

False

In [ ]:
a = 2
a < 4 # Contoh penggunaan operator <

True

In [ ]:
a = 2
4 > a

True

In [ ]:
a = 2
4 < a

False

In [ ]:
a = 2
a >= 4 # Contoh penggunaan operator >=

False

In [ ]:
a = 2
a <= 4 # Contoh penggunaan operator <=

True

In [ ]:
'HAI' == 'Hai' # Operator perbandingan untuk membandingkan string

In [ ]:
'HAI' != 'Hai'

In [ ]:
'B' > 'C'

In [ ]:
'C' > 'B'

In [ ]:
voucher = 'Yes'
# Penyataan kondisi
if voucher == 'Yes':
  
  # Perintah di dalam indentasi (ditulis menjorok ke dalam) yang dieksekusi jika kondisi terpenuhi
  print('berhasil')


In [ ]:
voucher = 'No'
# Penyataan kondisi
if voucher == 'Yes':
  
  # Perintah yang dieksekusi jika kondisi terpenuh
  print('berhasil')

In [ ]:
voucher = 'No'
# Penyataan kondisi
if voucher == 'Yes':
  
  # Perintah yang dieksekusi jika kondisi terpenuhi
  print('berhasil')
  
# Perintah yang dieksekusi baik saat kondisi terpenuhi maupun tidak
print('Selamat!')

In [ ]:
voucher = 'Yes'
# Penyataan kondisi
if voucher == 'Yes':
  
  # Perintah yang dieksekusi jika kondisi terpenuhi
  print('berhasil')
  
# Perintah yang dieksekusi baik saat kondisi terpenuhi maupun tidak
print('Selamat !')

In [ ]:
voucher = 'Yes'
# Penyataan kondisi
if voucher == 'Yes':
  
  # Perintah yang dieksekusi jika kondisi terpenuhi
  print('berhasil')

else:
	
  # perintah yang dieksekusi jika kondisi tidak terpenuhi
	print('beli voucher dahulu')

print('Selamat!')

In [ ]:
voucher = 'No'
# Penyataan kondisi
if voucher == 'Yes':

  # Perintah yang dieksekusi jika kondisi terpenuhi
  print('berhasil')
else:

	# perintah yang dieksekusi jika kondisi tidak terpenuhi
	print('beli voucher dahulu')
 
print('Selamat!')

In [ ]:
x = 2
if (x % 2 == 1):
  print(x, 'adalah bilangan ganjil')
else:
  print(x, 'adalah bilangan genap')

In [ ]:
usia = 20
if (usia > 20):
  print('Silahkan masuk ke ruang A')
elif (usia == 20):
  print('Silahkan masuk ke ruang B')
else:
  print('Anda tidak boleh masuk')

In [ ]:
biaya = 30000

if (biaya > 10000):
    biaya = biaya - (biaya * 0.15)
    print('diskon 15%')
  
elif(biaya == 20000):
    biaya = biaya - (biaya * 0.1)
    print('diskon 10%')
 
else:
	  biaya = biaya

print('Total yang harus dibayar adalah Rp. {:.0f}'.format(biaya))
print('\nTerima kasih!')

In [ ]:
# Contoh penggunaan operator logika 'and'
angka = 90
if (angka>= 80):
	 nilai = 'A'
elif (angka>= 70 and angka< 80):
 	nilai = 'B'
elif (angka>= 60 and angka< 70):
 	nilai = 'C'
elif (angka>= 50 and angka< 60):
 	nilai = 'D'
elif (angka< 50):
 	nilai = 'E'
 
print('Nilai akhir adalah ', nilai) 

In [ ]:
# Contoh penggunaan operator logika 'or'
nilai = 'B'
if (nilai == 'A' or nilai == 'B' or nilai == 'C'):
 	print('Berhasil!')
else:
 	print('Gagal')

In [ ]:
# Contoh penggunaan operator logika 'not'
nilai = 80
if not nilai == 85:
	print('Gagal!')
else:
	print('Berhasil!')

Fungsi

In [ ]:
# Contoh fungsi untuk menambah nilai dengan angka 2
def tambah_dua(a):
	b = a + 2
	return b
# Memanggil fungsi tambah_dua
tambah_dua(1)

In [ ]:
# Contoh fungsi perkalian dua bilangan
def perkalian(x, y):
	z = x * y
	return print(x, 'dikali', y, 'sama dengan ', z)
# Memanggil fungsi perkalian
perkalian(2,3)

In [ ]:
a1 = 2
b1 = 3
c1 = a1 * 3 + b1 * 4

if (c1 > 25):
  c1 = c1
else:
  c1 = 0

In [ ]:
a2 = 5
b2 = 6
c2 = a2 * 3 + b2 * 4

if (c2 > 25):
  c2 = c2
else:
  c2 = 0

In [ ]:
# Fungsi untuk menghitung a dan b
def hitung_ab(a, b):
  c = a * 3 + b * 4
  
  if (c > 25):
   c = c
   
  else:
   c = 0
  
  return c

In [ ]:
a1 = 2
b1 = 3
c1 = hitung_ab(a1, b1)
c1

In [ ]:
a2 = 5
b2 = 4
c2 = hitung_ab(a2, b2)
c2

In [ ]:
# Contoh penggunaan variabel global dan local
kota_asal = 'Bogor'

def kota(kota_asal):
  kota_indo = kota_asal
  print(kota_indo, 'adalah salah satu kota di Indonesia')
kota(kota_asal)

In [ ]:
kota_asal = 'Bogor'
def kota(kota_asal):
  global kota_indo
  kota_indo = 'Jakarta Timur'
  print(kota_asal, 'adalah salah satu kota di Indonesia')
  
kota(kota_asal)
kota(kota_indo)

In [ ]:
# Contoh fungsi dengan if...else
def bio(nama, pelajaran, nilai):
  print(nama, pelajaran, nilai)
  
  if (nilai > 75):
    return 'Selamat Anda Lulus!'
  else:
    return 'Mohon Maaf, Anda Tidak Lulus!'

# Panggil fungsi dan definisikan ke variabel x
x = bio('Agus', 'Kalkulus', 85)
print(x)

In [ ]:
# Contoh fungsi dengan perulangan for
def list_film(film):
	 for item in film:
		 print(item)
   
# Panggil fungsi
list_film(['The Avengers', 'Amazing Spiderman', 'Dr. Strange'])

In [ ]:
# Contoh fungsi dengan argumen default
def nilai_akhir(nilai = 50):
  if (nilai < 60):
    print('Nilai = ', nilai)
    print('Remedial!')
  else:
    print('Nilai = ', nilai)
    print('Anda Lulus!')
    
# Memanggil fungsi dengan argument
nilai_akhir(80)

Nilai =  80
Anda Lulus!


In [ ]:
# Memanggil fungsi tanpa argument
nilai_akhir()

Nilai =  50
Remedial!


In [ ]:
# contoh penggunaan print
list = [10, 21, 34, 29, 56]
print(list)

[10, 21, 34, 29, 56]


In [ ]:
# contoh penggunaan len
list = [10, 21, 34, 29, 56]
len(list )

5

In [ ]:
# contoh penggunaan sum
list = [10, 21, 34, 29, 56]
sum(list)

150

In [ ]:
# contoh penggunaan min
list = [10, 21, 34, 29, 56]
min(list)

10

In [ ]:
# contoh penggunaan max
list = [10, 21, 34, 29, 56]
max(list)

56

In [ ]:
# contoh penggunaan sorted
list = [10, 21, 34, 29, 56]
sorted(list)

[10, 21, 29, 34, 56]

In [ ]:
#  contoh penggunaan type
list = [10, 21, 34, 29, 56]
type(list)

list

In [ ]:
# contoh penggunaan round
round(8.5666)

9

In [ ]:
# contoh penggunaan round
round(7.4)

7

In [ ]:
# contoh penggunaan abs
abs(-20/5)

4.0

Numpy 2 Dimensi

In [ ]:
# Import numpy
import numpy as np

In [ ]:
list_a = [[1, 2, 3], [4, 5, 6], [7, 8, 9]]
list_a

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [ ]:
A = np.array(list_a)
A

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [ ]:
A.ndim # Mengetahui dimensi array dari array A

2

In [ ]:
A.size # Mengecek jumlah elemen

9

In [ ]:
A.shape # Mengecek ukuran array di tiap dimensi

(3, 3)

In [ ]:
A.dtype # Mengecek tipe data array

dtype('int64')

In [ ]:
A[1, 1] # Mengambil elemen pada baris 2 kolom 2

5

In [ ]:
A[1, 2] # Mengambil elemen pada baris 2 kolom 3

6

In [ ]:
A[0, 2] # Mengambil elemen pada baris 1 kolom 3

3

In [ ]:
A[1][:3] # Mengambil elemen pada baris 2 kolom 1-3

array([4, 5, 6])

In [ ]:
A[1, :3] # Mengambil elemen pada baris 2 kolom 1-3

array([4, 5, 6])

In [ ]:
A[1, :2] # Mengambil elemen pada baris 2 kolom 1-2

array([4, 5])

In [ ]:
A[0:, 1] # Mengambil elemen pada baris 1-3 kolom 2

array([2, 5, 8])

In [ ]:
A # Menampilkan array A

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [ ]:
A + 5 # Menjumlahkan array X dengan konstanta 5

array([[ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14]])

In [ ]:
X = np.array([[1, 2], [3, 4]]) # Membuat array 
X

array([[1, 2],
       [3, 4]])

In [ ]:
Y = np.array([[1, 3], [1, 2]]) # Membuat array Y
Y

array([[1, 3],
       [1, 2]])

In [ ]:
X + Y # Menjumlahkan array X dan Y

array([[2, 5],
       [4, 6]])

In [ ]:
X # Menampilkan array X
X * 3 # Mengalikan array X dengan 3

array([[ 3,  6],
       [ 9, 12]])

In [ ]:
X # Menampilkan array X
Y # Menampilkan array Y
X * Y # Mengalikan array X dan Y

array([[1, 6],
       [3, 8]])

In [ ]:
X # Menampilkan array X
Y # Menampilkan array Y
np.dot(X, Y) # Dot product dari array X dan Y

array([[ 3,  7],
       [ 7, 17]])